//! Confidence-based Brickell bridge prediction.
//!
//! Scoring is intentionally deterministic and inspectable. Each source gets a
//! signed weight, reliability and freshness factors are recorded separately,
//! and stale evidence remains visible in the explanation with a zero applied
//! score. Authoritative controller states bypass predictive thresholds only
//! while fresh. Entry and exit thresholds differ so a noisy sample near a
//! boundary does not make the public state oscillate.

use crate::{BrickellSchedule, ScheduleError, ScheduleStatus};
use bridgestatus_model::{
    Availability, AvailabilityStatus, BridgeControllerState, BridgeObservation,
    BridgeOperatingMode, BridgeState, Confidence, EtaRangeMinutes, Observation, ObservationId,
    OutboundProgressStage, SourceId, TimestampMillis, Urgency, VesselMovement,
};
use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use thiserror::Error;

/// Version stamped on every prediction generated by the shipped defaults.
/// One normalized bridge fact with policy-facing reliability metadata.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BridgeEvidence {
    /// Observation id used for traceability and deduplication.
    pub observation_id: ObservationId,
    /// Collector/source id used for corroboration accounting.
    pub source_id: SourceId,
    /// Time the upstream event occurred.
    pub observed_at: TimestampMillis,
    /// Optional hard expiration supplied by the collector.
    pub expires_at: Option<TimestampMillis>,
    /// Source health at collection time.
    pub availability: AvailabilityStatus,
    /// Source/classifier reliability independent of model confidence.
    pub reliability: Confidence,
    /// Typed bridge fact.
    pub fact: BridgeObservation,
}

impl BridgeEvidence {
    /// Converts a normalized bridge observation into predictor evidence.
    pub fn from_observation(observation: &Observation, reliability: Confidence) -> Self {
        Self {
            observation_id: observation.id.clone(),
            source_id: observation.source_id.clone(),
            observed_at: observation.observed_at,
            expires_at: observation.expires_at,
            availability: observation.availability.status,
            reliability,
            fact: observation.data.clone(),
        }
    }
}

/// Entry and exit threshold for one state.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct HysteresisThreshold {
    /// Score required to enter this state from below.
    pub enter: f32,
    /// Score below which an existing state exits.
    pub exit: f32,
}

/// Predictive state thresholds.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct BridgeThresholds {
    /// Threshold for `watch`.
    pub watch: HysteresisThreshold,
    /// Threshold for `likely`.
    pub likely: HysteresisThreshold,
}

impl Default for BridgeThresholds {
    fn default() -> Self {
        Self {
            watch: HysteresisThreshold {
                enter: 0.18,
                exit: 0.10,
            },
            likely: HysteresisThreshold {
                enter: 0.58,
                exit: 0.45,
            },
        }
    }
}

/// Signed source weights before reliability, decay, and legal context.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct EvidenceWeights {
    /// Weekday scheduled-window context.
    pub schedule_scheduled: f32,
    /// On-signal context outside weekday restrictions.
    pub schedule_on_signal: f32,
    /// Blackout context (kept small because exceptions still exist).
    pub schedule_blackout: f32,
    /// Strong approaching AIS track.
    pub ais_approaching: f32,
    /// AIS track moving away or leaving the route.
    pub ais_diverging: f32,
    /// Vessel holding position near the approach.
    pub ais_stationary: f32,
    /// Ordered movement through at least two upstream bridges toward Brickell.
    pub outbound_high: f32,
    /// Ordered movement has reached the nearest observed upstream bridge.
    pub outbound_very_high: f32,
    /// A booked river transit that the bridge schedule cannot refuse.
    pub transit_exempt: f32,
    /// A booked river transit subject to the ordinary schedule.
    pub transit_ordinary: f32,
    /// Bonus for at least two independent positive predictive sources.
    pub corroboration_bonus: f32,
}

impl Default for EvidenceWeights {
    fn default() -> Self {
        Self {
            schedule_scheduled: 0.08,
            schedule_on_signal: 0.0,
            schedule_blackout: 0.0,
            ais_approaching: 0.46,
            ais_diverging: -0.32,
            ais_stationary: 0.04,
            outbound_high: 0.68,
            outbound_very_high: 0.88,
            transit_exempt: 0.72,
            transit_ordinary: 0.5,
            corroboration_bonus: 0.08,
        }
    }
}

/// Inspectable discounts applied to evidence weights.
#[derive(Clone, Copy, Debug, PartialEq, Serialize, Deserialize)]
pub struct EvidenceFactors {
    /// ETA begins within fifteen minutes.
    pub ais_eta_near: f32,
    /// ETA begins within twenty-five minutes.
    pub ais_eta_mid: f32,
    /// ETA begins later than twenty-five minutes.
    pub ais_eta_far: f32,
    /// AIS item has no ETA.
    pub ais_eta_unknown: f32,
    /// Vessel has no known opening history.
    pub ais_propensity_unknown: f32,
}

impl Default for EvidenceFactors {
    fn default() -> Self {
        Self {
            ais_eta_near: 1.0,
            ais_eta_mid: 0.75,
            ais_eta_far: 0.40,
            ais_eta_unknown: 0.65,
            ais_propensity_unknown: 0.75,
        }
    }
}

/// Exponential half-life and hard stale horizon for an evidence class.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct DecayRule {
    /// Age at which an otherwise valid contribution is halved.
    pub half_life_seconds: u32,
    /// Age at which the contribution is ignored completely.
    pub stale_after_seconds: u32,
}

/// Freshness behavior by evidence class.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct EvidenceDecay {
    /// AIS track decay.
    pub ais: DecayRule,
    /// Upstream progression decay.
    pub upstream: DecayRule,
    /// Authoritative controller decay.
    pub controller: DecayRule,
}

impl Default for EvidenceDecay {
    fn default() -> Self {
        Self {
            ais: DecayRule {
                half_life_seconds: 5 * 60,
                stale_after_seconds: 20 * 60,
            },
            upstream: DecayRule {
                half_life_seconds: 6 * 60,
                stale_after_seconds: 24 * 60,
            },
            controller: DecayRule {
                half_life_seconds: 45,
                stale_after_seconds: 3 * 60,
            },
        }
    }
}

/// User-inspectable predictor configuration.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BridgePredictorConfig {
    /// State thresholds with hysteresis.
    pub thresholds: BridgeThresholds,
    /// Explainable signed source weights.
    pub weights: EvidenceWeights,
    /// Source-specific freshness rules.
    pub decay: EvidenceDecay,
    /// Discounts for incomplete or less-immediate evidence.
    pub factors: EvidenceFactors,
    /// Extra schedule weight as a scheduled opening slot approaches, when
    /// vessels that have been refused are waiting to be released together.
    pub schedule_slot_imminent: f32,
    /// How close a scheduled slot must be, in minutes, to count as imminent.
    pub schedule_slot_window_minutes: i64,
    /// Factor applied to predictive AIS/upstream evidence during blackouts.
    /// This is not zero because exception traffic can open at any time.
    pub blackout_predictive_factor: f32,
}

impl Default for BridgePredictorConfig {
    fn default() -> Self {
        Self {
            thresholds: BridgeThresholds::default(),
            weights: EvidenceWeights::default(),
            decay: EvidenceDecay::default(),
            factors: EvidenceFactors::default(),
            schedule_slot_imminent: 0.22,
            schedule_slot_window_minutes: 12,
            blackout_predictive_factor: 0.75,
        }
    }
}

/// Invalid predictor configuration or schedule evaluation.
#[derive(Debug, Error)]
pub enum PredictionError {
    /// Schedule conversion failed.
    #[error(transparent)]
    Schedule(#[from] ScheduleError),
    /// A threshold was outside `0..=1` or had an exit above its entry.
    #[error("invalid hysteresis thresholds")]
    InvalidThresholds,
    /// Threshold entry values were not strictly increasing.
    #[error("state entry thresholds must increase from watch to likely")]
    UnorderedThresholds,
    /// A decay rule had a zero half-life or a stale horizon shorter than it.
    #[error("invalid evidence decay rule")]
    InvalidDecay,
    /// Blackout predictive factor was outside `0..=1`.
    #[error("blackout predictive factor must be between zero and one")]
    InvalidBlackoutFactor,
    /// An evidence discount was outside `0..=1`.
    #[error("evidence factors must be between zero and one")]
    InvalidEvidenceFactor,
}

/// Low-cardinality evidence label used in explanations and telemetry.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EvidenceKind {
    /// Locally evaluated legal schedule.
    Schedule,
    /// AIS approach or divergence.
    Ais,
    /// Ordered outbound bridge progression.
    Outbound,
    /// Controller-backed ground truth.
    Controller,
    /// A transit booked on the pilots' dispatch board.
    Transit,
    /// Independent-source corroboration bonus.
    Corroboration,
}

/// Why a potential contribution did or did not affect the score.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ContributionDisposition {
    /// Applied to the predictive score.
    Applied,
    /// Hard expiration or class stale horizon was exceeded.
    Stale,
    /// Source was offline or disabled at collection time.
    Unavailable,
    /// Fact is visible but has no positive or negative scoring meaning.
    Informational,
    /// Fresh ground truth directly selected the domain state.
    Authoritative,
}

/// Complete arithmetic for one evidence contribution.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ScoreContribution {
    /// Source observation, or `None` for schedule/corroboration terms.
    pub observation_id: Option<ObservationId>,
    /// Collector source, or `None` for locally generated terms.
    pub source_id: Option<SourceId>,
    /// Evidence class.
    pub kind: EvidenceKind,
    /// Human-readable, non-secret explanation.
    pub label: String,
    /// Signed configured weight before factors.
    pub raw_weight: f32,
    /// User/source reliability factor.
    pub reliability_factor: f32,
    /// Exponential freshness factor.
    pub freshness_factor: f32,
    /// Schedule compatibility factor.
    pub context_factor: f32,
    /// Final signed score added before clamping.
    pub applied_score: f32,
    /// Whether and why it affected the result.
    pub disposition: ContributionDisposition,
}

/// Whether hysteresis affected this evaluation.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct PredictionTransition {
    /// Previous published bridge state, if supplied.
    pub previous: Option<BridgeState>,
    /// Current state.
    pub current: BridgeState,
    /// Whether the public domain state changed.
    pub changed: bool,
    /// True when the current score was below an entry threshold but above the
    /// exit threshold for the previous state.
    pub held_by_hysteresis: bool,
}

/// Explainable result of one model evaluation.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct BridgePrediction {
    /// Evaluation instant.
    pub evaluated_at: TimestampMillis,
    /// Public bridge domain state.
    pub state: BridgeState,
    /// Normalized, clamped score.
    pub confidence: Confidence,
    /// Attention policy derived from the bridge state.
    pub urgency: Urgency,
    /// Health of the predictive source set.
    pub availability: Availability,
    /// Best current time-to-bridge range from positive evidence.
    pub eta: Option<EtaRangeMinutes>,
    /// Legal context; never itself proof of an opening.
    pub schedule: ScheduleStatus,
    /// Full arithmetic, including ignored/stale evidence.
    pub contributions: Vec<ScoreContribution>,
    /// Public state transition details.
    pub transition: PredictionTransition,
}

/// Deterministic Brickell predictor.
#[derive(Clone, Debug)]
pub struct BridgePredictor {
    config: BridgePredictorConfig,
    schedule: BrickellSchedule,
}

impl BridgePredictor {
    /// Constructs a predictor and validates all policy bounds.
    pub fn new(config: BridgePredictorConfig) -> Result<Self, PredictionError> {
        validate_config(&config)?;
        Ok(Self {
            config,
            schedule: BrickellSchedule::new()?,
        })
    }

    /// Returns the immutable configuration.
    pub fn config(&self) -> &BridgePredictorConfig {
        &self.config
    }

    /// Evaluates evidence at `now`, optionally applying hysteresis from the
    /// previously published prediction.
    pub fn evaluate(
        &self,
        now: TimestampMillis,
        evidence: &[BridgeEvidence],
        previous: Option<&BridgePrediction>,
    ) -> Result<BridgePrediction, PredictionError> {
        let schedule = self.schedule.evaluate(now)?;
        // An exempt transit makes the blackout inapplicable rather than merely
        // less severe: the bridge opens for a tug with a tow at any hour. Score
        // the rest of the evidence as if the blackout were not in force, while
        // still reporting the real mode so the explanation stays truthful.
        let exempt_transit = evidence.iter().any(|item| {
            if !evidence_is_active(item, now, self.config.decay.upstream) {
                return false;
            }
            match &item.fact {
                // Stated: the pilots booked a tug-assisted tow.
                BridgeObservation::ScheduledTransit { exempt, .. } => *exempt,
                // Inferred: a bascule went up while the blackout was in force.
                // Ordinary traffic would have been refused, so whatever moved
                // was exempt. This inference has to exist because the pilots'
                // board is only one source of commercial traffic -- plenty of
                // commercial movements never appear on it, and keying the
                // exemption solely to that board would miss them.
                BridgeObservation::OutboundProgress { .. } => {
                    schedule.mode == BridgeOperatingMode::Blackout
                }
                _ => false,
            }
        });
        let scoring_mode = if exempt_transit && schedule.mode == BridgeOperatingMode::Blackout {
            BridgeOperatingMode::OnSignal
        } else {
            schedule.mode
        };
        // Traffic refused during a restricted period does not disperse; it
        // queues and leaves together on the hour or half-hour. The minutes
        // before a slot are therefore the likeliest time for an opening, which
        // a flat schedule weight cannot express.
        let minutes_to_slot = schedule
            .next_ordinary_opening_at
            .map(|slot| (slot.0.saturating_sub(now.0)) / 60_000);
        let slot_imminent = minutes_to_slot.is_some_and(|minutes| {
            (0..=self.config.schedule_slot_window_minutes).contains(&minutes)
        });
        let mut contributions = vec![schedule_contribution(
            schedule.mode,
            exempt_transit,
            slot_imminent,
            &self.config,
        )];
        let mut positive_sources = BTreeSet::new();
        let mut positive_kinds = BTreeSet::new();
        let mut valid_non_schedule = 0usize;
        let mut stale_non_schedule = 0usize;
        let mut unavailable_non_schedule = 0usize;
        let mut last_success_at = None;
        let mut best_eta: Option<EtaRangeMinutes> = None;
        let mut latest_controller: Option<(&BridgeEvidence, BridgeControllerState)> = None;

        for item in evidence {
            if let BridgeObservation::Controller { state } = &item.fact
                && evidence_is_active(item, now, self.config.decay.controller)
                && latest_controller
                    .as_ref()
                    .is_none_or(|(current, _)| item.observed_at > current.observed_at)
            {
                latest_controller = Some((item, *state));
            }

            let scored = self.score_evidence(item, now, scoring_mode);
            match scored.disposition {
                ContributionDisposition::Applied
                | ContributionDisposition::Informational
                | ContributionDisposition::Authoritative => {
                    if scored.kind != EvidenceKind::Schedule {
                        valid_non_schedule += 1;
                        if last_success_at.is_none_or(|last| item.observed_at > last) {
                            last_success_at = Some(item.observed_at);
                        }
                    }
                    if scored.applied_score > 0.0 {
                        positive_sources.insert(item.source_id.clone());
                        positive_kinds.insert(scored.kind);
                        if let Some(eta) = evidence_eta(&item.fact, item.observed_at, now)
                            && best_eta.is_none_or(|current| eta.earliest < current.earliest)
                        {
                            best_eta = Some(eta);
                        }
                    }
                }
                ContributionDisposition::Stale => stale_non_schedule += 1,
                ContributionDisposition::Unavailable => unavailable_non_schedule += 1,
            }
            contributions.push(scored);
        }

        if positive_sources.len() >= 2 && positive_kinds.len() >= 2 {
            contributions.push(ScoreContribution {
                observation_id: None,
                source_id: None,
                kind: EvidenceKind::Corroboration,
                label: "independent predictive sources corroborate".into(),
                raw_weight: self.config.weights.corroboration_bonus,
                reliability_factor: 1.0,
                freshness_factor: 1.0,
                context_factor: 1.0,
                applied_score: self.config.weights.corroboration_bonus,
                disposition: ContributionDisposition::Applied,
            });
        }

        let raw_score = contributions
            .iter()
            .map(|item| item.applied_score)
            .sum::<f32>()
            .clamp(0.0, 1.0);
        let schedule_only = positive_kinds.is_empty();

        let authoritative = authoritative_state(latest_controller);
        let (state, confidence, held_by_hysteresis) =
            if let Some((state, certainty)) = authoritative {
                (state, certainty, false)
            } else {
                let (mut selected, held) = select_predictive_state(
                    raw_score,
                    previous.map(|item| item.state),
                    self.config.thresholds,
                );
                // A clock window is context, never predictive proof. This cap also
                // applies when the only other facts were stale/unavailable.
                if schedule_only && selected > BridgeState::Watch {
                    selected = BridgeState::Watch;
                }
                (selected, Confidence::from_score(raw_score), held)
            };

        let previous_state = previous.map(|item| item.state);
        let availability = prediction_availability(
            now,
            evidence,
            valid_non_schedule,
            stale_non_schedule,
            unavailable_non_schedule,
            last_success_at,
        );

        Ok(BridgePrediction {
            evaluated_at: now,
            state,
            confidence,
            urgency: urgency_for(state),
            availability,
            eta: self.scheduled_eta(best_eta, now, exempt_transit)?,
            schedule,
            contributions,
            transition: PredictionTransition {
                previous: previous_state,
                current: state,
                changed: previous_state != Some(state),
                held_by_hysteresis,
            },
        })
    }

    /// Pushes a predicted arrival out to when the bridge may actually open.
    ///
    /// The arrival window says when a vessel reaches the bridge. During the
    /// hour/half-hour period that is not when the bridge opens: an ordinary
    /// vessel arriving at 18:32 waits for 19:00. Reporting the arrival as the
    /// opening promises a time the bridge legally cannot open, which is worse
    /// than reporting nothing.
    ///
    /// Exempt traffic is left alone. A tug with a tow opens the bridge when it
    /// gets there, which is the entire point of the exemption.
    fn scheduled_eta(
        &self,
        eta: Option<EtaRangeMinutes>,
        now: TimestampMillis,
        exempt_transit: bool,
    ) -> Result<Option<EtaRangeMinutes>, PredictionError> {
        let Some(eta) = eta else {
            return Ok(None);
        };
        if exempt_transit {
            return Ok(Some(eta));
        }
        let shift = |minutes: u16| -> Result<u16, PredictionError> {
            let arrival = TimestampMillis::new(
                now.0
                    .saturating_add(i64::from(minutes).saturating_mul(60_000)),
            );
            let Some(slot) = self.schedule.ordinary_opening_at_or_after(arrival)? else {
                return Ok(minutes);
            };
            let waited = (slot.0.saturating_sub(now.0)) / 60_000;
            Ok(u16::try_from(waited).unwrap_or(u16::MAX).max(minutes))
        };
        Ok(Some(EtaRangeMinutes::new(
            shift(eta.earliest)?,
            shift(eta.latest)?,
        )))
    }

    fn score_evidence(
        &self,
        item: &BridgeEvidence,
        now: TimestampMillis,
        mode: BridgeOperatingMode,
    ) -> ScoreContribution {
        let (kind, raw_weight, label, decay) = classify_fact(item, &self.config);
        let availability_factor = availability_factor(item.availability);
        let age_seconds = item.observed_at.age_seconds_at(now);
        let explicitly_expired = item.expires_at.is_some_and(|expires| expires < now);
        // Predictive evidence that carries its own arrival window does not get
        // less true while that window is still ahead. An upstream opening says a
        // vessel will reach the target in N minutes; decaying it from the moment
        // it was seen scores the prediction lowest exactly when it is about to
        // come true. Age it from the close of its window instead.
        let pending_seconds = predicted_window_seconds(&item.fact);
        let effective_age = age_seconds.saturating_sub(pending_seconds);
        let stale = explicitly_expired
            || item.availability == AvailabilityStatus::Stale
            || effective_age > u64::from(decay.stale_after_seconds);
        let freshness_factor = if stale {
            0.0
        } else {
            2.0_f32.powf(-(effective_age as f32) / decay.half_life_seconds as f32)
        };
        // A blackout describes what the bridge will do for *ordinary* traffic,
        // and it discounts evidence about vessels that may simply be refused.
        //
        // It never applies to an observed upstream opening. That is a bascule
        // that already went up for a vessel already under way, and a vessel
        // that got a bridge raised during rush hour is exactly the exempt kind
        // -- a tug with a tow -- which Brickell must also open for. Discounting
        // it would hide the openings the blackout least predicts.
        let context_factor = if mode == BridgeOperatingMode::Blackout
            && kind == EvidenceKind::Ais
            && raw_weight > 0.0
        {
            self.config.blackout_predictive_factor
        } else {
            1.0
        };
        let disposition = if stale {
            ContributionDisposition::Stale
        } else if availability_factor == 0.0 {
            ContributionDisposition::Unavailable
        } else if raw_weight == 0.0 {
            ContributionDisposition::Informational
        } else if kind == EvidenceKind::Controller
            && matches!(
                &item.fact,
                BridgeObservation::Controller {
                    state: BridgeControllerState::Open
                }
            )
        {
            ContributionDisposition::Authoritative
        } else {
            ContributionDisposition::Applied
        };
        let applied_score = if matches!(
            disposition,
            ContributionDisposition::Applied | ContributionDisposition::Authoritative
        ) {
            raw_weight
                * item.reliability.as_score()
                * availability_factor
                * freshness_factor
                * context_factor
        } else {
            0.0
        };

        ScoreContribution {
            observation_id: Some(item.observation_id.clone()),
            source_id: Some(item.source_id.clone()),
            kind,
            label,
            raw_weight,
            reliability_factor: item.reliability.as_score() * availability_factor,
            freshness_factor,
            context_factor,
            applied_score,
            disposition,
        }
    }
}

impl Default for BridgePredictor {
    fn default() -> Self {
        Self::new(BridgePredictorConfig::default())
            .expect("shipped predictor configuration and IANA zone are valid")
    }
}

fn validate_config(config: &BridgePredictorConfig) -> Result<(), PredictionError> {
    let thresholds = [config.thresholds.watch, config.thresholds.likely];
    if thresholds
        .iter()
        .any(|item| !(0.0..=1.0).contains(&item.enter) || !(0.0..=item.enter).contains(&item.exit))
    {
        return Err(PredictionError::InvalidThresholds);
    }
    if thresholds[0].enter >= thresholds[1].enter {
        return Err(PredictionError::UnorderedThresholds);
    }
    let decay = [
        config.decay.ais,
        config.decay.upstream,
        config.decay.controller,
    ];
    if decay.iter().any(|item| {
        item.half_life_seconds == 0 || item.stale_after_seconds < item.half_life_seconds
    }) {
        return Err(PredictionError::InvalidDecay);
    }
    if !(0.0..=1.0).contains(&config.blackout_predictive_factor) {
        return Err(PredictionError::InvalidBlackoutFactor);
    }
    let factors = [
        config.factors.ais_eta_near,
        config.factors.ais_eta_mid,
        config.factors.ais_eta_far,
        config.factors.ais_eta_unknown,
        config.factors.ais_propensity_unknown,
    ];
    if factors.iter().any(|factor| !(0.0..=1.0).contains(factor)) {
        return Err(PredictionError::InvalidEvidenceFactor);
    }
    Ok(())
}

fn schedule_contribution(
    mode: BridgeOperatingMode,
    exempt_transit: bool,
    slot_imminent: bool,
    config: &BridgePredictorConfig,
) -> ScoreContribution {
    let weights = &config.weights;
    if mode == BridgeOperatingMode::Blackout && exempt_transit {
        return ScoreContribution {
            observation_id: None,
            source_id: None,
            kind: EvidenceKind::Schedule,
            label: "a booked tug-assisted transit is exempt from the traffic blackout".into(),
            raw_weight: weights.schedule_on_signal,
            reliability_factor: 1.0,
            freshness_factor: 1.0,
            context_factor: 1.0,
            applied_score: weights.schedule_on_signal,
            disposition: ContributionDisposition::Applied,
        };
    }
    let (raw_weight, label) = match mode {
        BridgeOperatingMode::OnSignal => (
            weights.schedule_on_signal,
            "ordinary openings are currently on signal",
        ),
        BridgeOperatingMode::Scheduled if slot_imminent => (
            weights.schedule_scheduled + config.schedule_slot_imminent,
            "a scheduled opening slot is imminent and refused traffic waits for it",
        ),
        BridgeOperatingMode::Scheduled => (
            weights.schedule_scheduled,
            "weekday hour/half-hour schedule applies",
        ),
        BridgeOperatingMode::Blackout if slot_imminent => (
            weights.schedule_blackout + config.schedule_slot_imminent,
            "the blackout ends shortly and refused traffic is waiting",
        ),
        BridgeOperatingMode::Blackout => (
            weights.schedule_blackout,
            "ordinary weekday openings are in a traffic blackout",
        ),
    };
    ScoreContribution {
        observation_id: None,
        source_id: None,
        kind: EvidenceKind::Schedule,
        label: label.into(),
        raw_weight,
        reliability_factor: 1.0,
        freshness_factor: 1.0,
        context_factor: 1.0,
        applied_score: raw_weight,
        disposition: ContributionDisposition::Applied,
    }
}

fn classify_fact(
    evidence: &BridgeEvidence,
    config: &BridgePredictorConfig,
) -> (EvidenceKind, f32, String, DecayRule) {
    match &evidence.fact {
        BridgeObservation::AisTrack {
            movement,
            route_intersects,
            eta,
            opening_propensity,
            ..
        } => {
            let weight = match movement {
                VesselMovement::Approaching if *route_intersects => {
                    let eta_factor = match eta {
                        Some(eta) if eta.earliest <= 15 => config.factors.ais_eta_near,
                        Some(eta) if eta.earliest <= 25 => config.factors.ais_eta_mid,
                        Some(_) => config.factors.ais_eta_far,
                        None => config.factors.ais_eta_unknown,
                    };
                    let propensity_factor = opening_propensity
                        .map(|value| 0.50 + 0.50 * value.as_score())
                        .unwrap_or(config.factors.ais_propensity_unknown);
                    config.weights.ais_approaching * eta_factor * propensity_factor
                }
                VesselMovement::Diverging => config.weights.ais_diverging,
                VesselMovement::Approaching => config.weights.ais_diverging * 0.5,
                VesselMovement::Stationary => config.weights.ais_stationary,
                VesselMovement::Unknown => 0.0,
            };
            (
                EvidenceKind::Ais,
                weight,
                match movement {
                    VesselMovement::Approaching if *route_intersects => {
                        "AIS vessel approaching on an intersecting route"
                    }
                    VesselMovement::Approaching => {
                        "AIS vessel approaching but projected route misses bridge"
                    }
                    VesselMovement::Diverging => "AIS vessel is diverging",
                    VesselMovement::Stationary => "AIS vessel is holding position",
                    VesselMovement::Unknown => "AIS movement is not yet classified",
                }
                .into(),
                config.decay.ais,
            )
        }
        BridgeObservation::OutboundProgress { stage, .. } => (
            EvidenceKind::Outbound,
            match stage {
                OutboundProgressStage::High => config.weights.outbound_high,
                OutboundProgressStage::VeryHigh => config.weights.outbound_very_high,
            },
            match stage {
                OutboundProgressStage::High => {
                    "ordered upstream openings indicate outbound progression"
                }
                OutboundProgressStage::VeryHigh => {
                    "outbound progression reached the nearest upstream bridge"
                }
            }
            .into(),
            config.decay.upstream,
        ),
        BridgeObservation::ScheduledTransit { exempt, .. } => (
            EvidenceKind::Transit,
            if *exempt {
                config.weights.transit_exempt
            } else {
                config.weights.transit_ordinary
            },
            if *exempt {
                "the pilots' board has a tug-assisted river transit booked, which the schedule cannot refuse"
            } else {
                "the pilots' board has a river transit booked"
            }
            .into(),
            config.decay.upstream,
        ),
        BridgeObservation::Controller { state } => (
            EvidenceKind::Controller,
            match state {
                BridgeControllerState::Open => 1.0,
                BridgeControllerState::Closed | BridgeControllerState::Unknown => 0.0,
            },
            format!("authoritative controller reports {state:?}").to_ascii_lowercase(),
            config.decay.controller,
        ),
    }
}

fn evidence_is_active(evidence: &BridgeEvidence, now: TimestampMillis, decay: DecayRule) -> bool {
    matches!(
        evidence.availability,
        AvailabilityStatus::Live | AvailabilityStatus::Degraded
    ) && !evidence.expires_at.is_some_and(|expires| expires < now)
        && evidence.observed_at.age_seconds_at(now) <= u64::from(decay.stale_after_seconds)
}

fn evidence_eta(
    fact: &BridgeObservation,
    observed_at: TimestampMillis,
    now: TimestampMillis,
) -> Option<EtaRangeMinutes> {
    let eta = match fact {
        BridgeObservation::AisTrack { eta, .. }
        | BridgeObservation::OutboundProgress { eta, .. }
        | BridgeObservation::ScheduledTransit { eta, .. } => *eta,
        _ => None,
    }?;
    let elapsed = u16::try_from(observed_at.age_seconds_at(now) / 60).unwrap_or(u16::MAX);
    (elapsed <= eta.latest).then(|| {
        EtaRangeMinutes::new(
            eta.earliest.saturating_sub(elapsed),
            eta.latest.saturating_sub(elapsed),
        )
    })
}

/// A vessel that has reached the bridge and cannot pass does not leave; it
/// waits. Restricted-period openings are on the hour and half-hour, so a
/// transit that arrives at 15:40 can sit until 16:00 with the queue growing
/// behind it.
const QUEUE_GRACE_SECONDS: u64 = 20 * 60;

/// How long a fact's own prediction stays pending, in seconds.
///
/// Zero for evidence that makes no forward claim, which leaves ordinary
/// age-based decay untouched for everything else.
///
/// For an upstream opening this covers both halves of the vessel's journey: the
/// run down to the target, then the wait at it. Evidence that a vessel is
/// *queued* at the bridge is stronger than evidence it is on its way, so the
/// contribution must not fade in between. Nothing here needs to expire the
/// evidence when the vessel finally passes -- the detector stops reporting
/// progress as soon as the target opens, which is what consumes it.
fn predicted_window_seconds(fact: &BridgeObservation) -> u64 {
    match fact {
        BridgeObservation::OutboundProgress { eta, .. } => {
            eta.map_or(0, |eta| u64::from(eta.latest) * 60) + QUEUE_GRACE_SECONDS
        }
        // AIS tracks keep plain age decay. A position report is a statement
        // about where a vessel was, and a newer one always supersedes it, so
        // age is the right measure there. An upstream bridge opening has no
        // successor report -- nothing arrives to replace it until the target
        // itself moves -- which is why only that class needs the window.
        _ => 0,
    }
}

fn availability_factor(status: AvailabilityStatus) -> f32 {
    match status {
        AvailabilityStatus::Live => 1.0,
        AvailabilityStatus::Degraded => 0.75,
        AvailabilityStatus::Stale | AvailabilityStatus::Offline | AvailabilityStatus::Disabled => {
            0.0
        }
    }
}

fn authoritative_state(
    controller: Option<(&BridgeEvidence, BridgeControllerState)>,
) -> Option<(BridgeState, Confidence)> {
    match controller.map(|(_, state)| state) {
        Some(BridgeControllerState::Open) => Some((BridgeState::Open, Confidence::CERTAIN)),
        Some(BridgeControllerState::Closed | BridgeControllerState::Unknown) | None => None,
    }
}

fn select_predictive_state(
    score: f32,
    previous: Option<BridgeState>,
    thresholds: BridgeThresholds,
) -> (BridgeState, bool) {
    let candidate = if score >= thresholds.likely.enter {
        BridgeState::Likely
    } else if score >= thresholds.watch.enter {
        BridgeState::Watch
    } else {
        BridgeState::Clear
    };

    let held = match previous {
        Some(BridgeState::Likely) if score >= thresholds.likely.exit => BridgeState::Likely,
        Some(BridgeState::Watch) if score >= thresholds.watch.exit => BridgeState::Watch,
        _ => candidate,
    };

    (held.max(candidate), held > candidate)
}

fn prediction_availability(
    now: TimestampMillis,
    evidence: &[BridgeEvidence],
    valid: usize,
    stale: usize,
    unavailable: usize,
    last_success_at: Option<TimestampMillis>,
) -> Availability {
    let (status, detail) = if valid > 0 {
        (
            AvailabilityStatus::Live,
            if stale + unavailable > 0 {
                Some(format!(
                    "{valid} current bridge inputs; {} stale or unavailable",
                    stale + unavailable
                ))
            } else {
                None
            },
        )
    } else if evidence.is_empty() {
        (
            AvailabilityStatus::Degraded,
            Some("legal schedule only; predictive sources have no observations".into()),
        )
    } else if stale > 0 {
        (
            AvailabilityStatus::Stale,
            Some("all predictive observations are stale".into()),
        )
    } else if unavailable > 0 {
        let all_disabled = evidence
            .iter()
            .all(|item| item.availability == AvailabilityStatus::Disabled);
        (
            if all_disabled {
                AvailabilityStatus::Disabled
            } else {
                AvailabilityStatus::Offline
            },
            Some("predictive sources are unavailable".into()),
        )
    } else {
        (
            AvailabilityStatus::Degraded,
            Some("only non-predictive context is available".into()),
        )
    };
    Availability {
        status,
        checked_at: now,
        last_success_at,
        detail,
    }
}

fn urgency_for(state: BridgeState) -> Urgency {
    match state {
        BridgeState::Clear => Urgency::Passive,
        BridgeState::Watch => Urgency::Notice,
        BridgeState::Likely => Urgency::TimeSensitive,
        BridgeState::Open => Urgency::Critical,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use jiff::Timestamp;

    fn millis(text: &str) -> TimestampMillis {
        let timestamp: Timestamp = text.parse().expect("valid timestamp");
        TimestampMillis::new(timestamp.as_millisecond())
    }

    fn evidence(
        id: &str,
        source: &str,
        at: TimestampMillis,
        fact: BridgeObservation,
    ) -> BridgeEvidence {
        BridgeEvidence {
            observation_id: ObservationId::from(id),
            source_id: SourceId::from(source),
            observed_at: at,
            expires_at: None,
            availability: AvailabilityStatus::Live,
            reliability: Confidence::CERTAIN,
            fact,
        }
    }

    fn scheduled_now() -> TimestampMillis {
        millis("2026-08-14T19:10:00Z") // Friday 15:10 EDT, scheduled mode.
    }

    #[test]
    fn schedule_alone_does_not_create_a_prediction() {
        let prediction = BridgePredictor::default()
            .evaluate(scheduled_now(), &[], None)
            .expect("prediction");
        assert_eq!(prediction.state, BridgeState::Clear);
        assert_eq!(prediction.urgency, Urgency::Passive);
        assert_eq!(prediction.availability.status, AvailabilityStatus::Degraded);
    }

    #[test]
    fn runtime_strength_ais_plus_upstream_crosses_likely_threshold() {
        let now = scheduled_now();
        let mut ais = evidence(
            "ais-1",
            "local-ais",
            now,
            BridgeObservation::AisTrack {
                mmsi: Some("367000001".into()),
                vessel_name: Some("Test Vessel".into()),
                movement: VesselMovement::Approaching,
                route_intersects: true,
                eta: Some(EtaRangeMinutes::new(8, 12)),
                opening_propensity: None,
            },
        );
        ais.reliability = Confidence::from_basis_points(8_500);
        let mut upstream = evidence(
            "fl511-upstream",
            "fl511",
            now,
            BridgeObservation::OutboundProgress {
                bridge: "SW 2 Avenue".into(),
                stage: OutboundProgressStage::High,
                eta: Some(EtaRangeMinutes::new(9, 14)),
            },
        );
        upstream.reliability = Confidence::from_basis_points(3_500);
        let prediction = BridgePredictor::default()
            .evaluate(now, &[ais, upstream], None)
            .expect("prediction");

        assert_eq!(prediction.state, BridgeState::Likely);
        // 15:10 EDT is inside the hour/half-hour period, so an arrival eight to
        // twelve minutes out cannot open the bridge on arrival: the vessel
        // waits for 15:30, which is twenty minutes away. The window used to be
        // reported as the arrival, which promised a time the bridge could not
        // legally open.
        assert_eq!(prediction.eta, Some(EtaRangeMinutes::new(20, 20)));
        assert!(prediction.confidence.as_score() >= 0.58);
    }

    #[test]
    fn outbound_progress_maps_to_high_and_very_high_confidence() {
        let now = scheduled_now();
        for (stage, minimum) in [
            (OutboundProgressStage::High, 0.68),
            (OutboundProgressStage::VeryHigh, 0.88),
        ] {
            let outbound = evidence(
                "outbound-sequence",
                "fl511",
                now,
                BridgeObservation::OutboundProgress {
                    bridge: "SW 2 Avenue".into(),
                    stage,
                    eta: None,
                },
            );
            let prediction = BridgePredictor::default()
                .evaluate(now, &[outbound], None)
                .expect("prediction");
            assert_eq!(prediction.state, BridgeState::Likely);
            assert!(prediction.confidence.as_score() >= minimum);
        }
    }

    #[test]
    fn eta_is_aged_from_the_source_observation_time() {
        let now = scheduled_now();
        let observed_at = TimestampMillis(now.0 - 5 * 60 * 1_000);
        let fact = BridgeObservation::AisTrack {
            mmsi: None,
            vessel_name: None,
            movement: VesselMovement::Approaching,
            route_intersects: true,
            eta: Some(EtaRangeMinutes::new(8, 12)),
            opening_propensity: None,
        };

        assert_eq!(
            evidence_eta(&fact, observed_at, now),
            Some(EtaRangeMinutes::new(3, 7))
        );
        assert_eq!(
            evidence_eta(&fact, observed_at, TimestampMillis(now.0 + 8 * 60 * 1_000)),
            None
        );
    }

    #[test]
    fn fresh_controller_state_wins_over_predictive_evidence() {
        let now = scheduled_now();
        let diverging = evidence(
            "ais-diverging",
            "local-ais",
            now,
            BridgeObservation::AisTrack {
                mmsi: None,
                vessel_name: None,
                movement: VesselMovement::Diverging,
                route_intersects: false,
                eta: None,
                opening_propensity: None,
            },
        );
        let controller = evidence(
            "controller-open",
            "fl511",
            now,
            BridgeObservation::Controller {
                state: BridgeControllerState::Open,
            },
        );
        let prediction = BridgePredictor::default()
            .evaluate(now, &[diverging, controller], None)
            .expect("prediction");

        assert_eq!(prediction.state, BridgeState::Open);
        assert_eq!(prediction.confidence, Confidence::CERTAIN);
        assert_eq!(prediction.urgency, Urgency::Critical);
    }

    #[test]
    fn stale_authoritative_open_does_not_pin_state_open() {
        let now = scheduled_now();
        let old = TimestampMillis::new(now.0 - 4 * 60 * 1_000);
        let controller = evidence(
            "controller-old",
            "fl511",
            old,
            BridgeObservation::Controller {
                state: BridgeControllerState::Open,
            },
        );
        let prediction = BridgePredictor::default()
            .evaluate(now, &[controller], None)
            .expect("prediction");

        assert_eq!(prediction.state, BridgeState::Clear);
        assert_ne!(prediction.confidence, Confidence::CERTAIN);
    }

    #[test]
    fn fresh_closed_ground_truth_resolves_prior_open_state() {
        let predictor = BridgePredictor::default();
        let now = scheduled_now();
        let open = evidence(
            "controller-open",
            "fl511",
            now,
            BridgeObservation::Controller {
                state: BridgeControllerState::Open,
            },
        );
        let previous = predictor
            .evaluate(now, &[open], None)
            .expect("open prediction");
        let later = TimestampMillis::new(now.0 + 60_000);
        let closed = evidence(
            "controller-closed",
            "fl511",
            later,
            BridgeObservation::Controller {
                state: BridgeControllerState::Closed,
            },
        );
        let resolved = predictor
            .evaluate(later, &[closed], Some(&previous))
            .expect("resolved prediction");

        assert_eq!(resolved.state, BridgeState::Clear);
        assert!(resolved.transition.changed);
    }

    #[test]
    fn hysteresis_holds_likely_until_exit_threshold() {
        let predictor = BridgePredictor::default();
        let now = scheduled_now();
        let strong = evidence(
            "ais-strong",
            "local-ais",
            now,
            BridgeObservation::AisTrack {
                mmsi: None,
                vessel_name: None,
                movement: VesselMovement::Approaching,
                route_intersects: true,
                eta: Some(EtaRangeMinutes::new(8, 10)),
                opening_propensity: Some(Confidence::CERTAIN),
            },
        );
        let mut corroborating = evidence(
            "upstream-strong",
            "fl511",
            now,
            BridgeObservation::OutboundProgress {
                bridge: "Miami Avenue Bridge".into(),
                stage: OutboundProgressStage::High,
                eta: Some(EtaRangeMinutes::new(9, 12)),
            },
        );
        corroborating.reliability = Confidence::from_basis_points(3_500);
        let previous = predictor
            .evaluate(now, &[strong, corroborating], None)
            .expect("initial prediction");
        assert_eq!(previous.state, BridgeState::Likely);

        let mut weaker = evidence(
            "ais-weaker",
            "local-ais",
            now,
            BridgeObservation::AisTrack {
                mmsi: None,
                vessel_name: None,
                movement: VesselMovement::Approaching,
                route_intersects: true,
                eta: Some(EtaRangeMinutes::new(8, 10)),
                opening_propensity: Some(Confidence::CERTAIN),
            },
        );
        weaker.reliability = Confidence::from_basis_points(8_200);
        let held = predictor
            .evaluate(now, &[weaker], Some(&previous))
            .expect("hysteresis prediction");

        assert!(held.confidence.as_score() < predictor.config().thresholds.likely.enter);
        assert!(held.confidence.as_score() >= predictor.config().thresholds.likely.exit);
        assert_eq!(held.state, BridgeState::Likely);
        assert!(held.transition.held_by_hysteresis);
    }

    #[test]
    fn contribution_is_halved_at_its_half_life() {
        let predictor = BridgePredictor::default();
        let now = scheduled_now();
        let observed = TimestampMillis::new(
            now.0 - i64::from(predictor.config().decay.ais.half_life_seconds) * 1_000,
        );
        let ais = evidence(
            "ais-half-life",
            "local-ais",
            observed,
            BridgeObservation::AisTrack {
                mmsi: None,
                vessel_name: None,
                movement: VesselMovement::Approaching,
                route_intersects: true,
                eta: Some(EtaRangeMinutes::new(8, 10)),
                opening_propensity: Some(Confidence::CERTAIN),
            },
        );
        let prediction = predictor.evaluate(now, &[ais], None).expect("prediction");
        let contribution = prediction
            .contributions
            .iter()
            .find(|item| item.kind == EvidenceKind::Ais)
            .expect("AIS contribution");
        assert!((contribution.freshness_factor - 0.5).abs() < 0.001);
        assert!((contribution.applied_score - contribution.raw_weight * 0.5).abs() < 0.001);
    }

    /// Reproduces a false negative observed against the live river.
    ///
    /// SW 2 Ave opened at 15:31 as an outbound convoy worked downriver. At
    /// 15:52 eight vessels were queued at Brickell waiting for the next
    /// scheduled opening, and the app reported 8.6% confidence: weight 0.88
    /// decayed by a six-minute half-life over twenty-one minutes.
    ///
    /// An upstream opening is not an observation that rots. It is a prediction
    /// with a due time, and it is most informative as that time arrives.
    #[test]
    fn an_outbound_opening_does_not_decay_before_the_vessel_can_arrive() {
        let opened = millis("2026-08-15T19:31:59Z");
        let evaluated = millis("2026-08-15T19:52:08Z");
        let predictor = BridgePredictor::default();

        // SW 2 Ave is 759 m from Brickell: four to nine minutes at river speeds.
        let with_window = predictor
            .evaluate(
                evaluated,
                &[evidence(
                    "outbound-1",
                    "fl511.bridge.brickell",
                    opened,
                    BridgeObservation::OutboundProgress {
                        bridge: "SW 2 Ave".into(),
                        stage: OutboundProgressStage::VeryHigh,
                        eta: Some(EtaRangeMinutes::new(4, 9)),
                    },
                )],
                None,
            )
            .expect("prediction");

        let without_window = predictor
            .evaluate(
                evaluated,
                &[evidence(
                    "outbound-2",
                    "fl511.bridge.brickell",
                    opened,
                    BridgeObservation::OutboundProgress {
                        bridge: "SW 2 Ave".into(),
                        stage: OutboundProgressStage::VeryHigh,
                        eta: None,
                    },
                )],
                None,
            )
            .expect("prediction");

        assert!(
            with_window.confidence.basis_points > without_window.confidence.basis_points,
            "an arrival window must outscore bare age decay: {} vs {}",
            with_window.confidence.basis_points,
            without_window.confidence.basis_points
        );
        assert!(
            with_window.confidence.basis_points > 5_000,
            "a vessel due or queued at the bridge is not a 50/50: got {}",
            with_window.confidence.basis_points
        );
    }

    #[test]
    fn an_outbound_opening_still_expires_once_the_queue_grace_passes() {
        // The vessel has to be somewhere. Long after transit plus a plausible
        // wait, an opening that never happened stops being evidence.
        let opened = millis("2026-08-15T19:31:59Z");
        let much_later = millis("2026-08-15T21:20:00Z");
        let prediction = BridgePredictor::default()
            .evaluate(
                much_later,
                &[evidence(
                    "outbound-stale",
                    "fl511.bridge.brickell",
                    opened,
                    BridgeObservation::OutboundProgress {
                        bridge: "SW 2 Ave".into(),
                        stage: OutboundProgressStage::VeryHigh,
                        eta: Some(EtaRangeMinutes::new(4, 9)),
                    },
                )],
                None,
            )
            .expect("prediction");
        assert_eq!(prediction.state, BridgeState::Clear);
    }

    fn blackout_now() -> TimestampMillis {
        millis("2026-08-14T20:45:00Z") // Friday 16:45 EDT, inside the blackout.
    }

    fn outbound(at: TimestampMillis) -> BridgeEvidence {
        evidence(
            "outbound",
            "fl511.bridge.brickell",
            at,
            BridgeObservation::OutboundProgress {
                bridge: "SW 2 Ave".into(),
                stage: OutboundProgressStage::VeryHigh,
                eta: Some(EtaRangeMinutes::new(4, 9)),
            },
        )
    }

    #[test]
    fn a_blackout_does_not_discount_an_observed_upstream_opening() {
        // The bascule went up, so a vessel is already under way. Ordinary
        // traffic would have been refused during the blackout, which makes the
        // opening evidence of exempt traffic rather than a reason to doubt it.
        let predictor = BridgePredictor::default();
        let inside = predictor
            .evaluate(blackout_now(), &[outbound(blackout_now())], None)
            .expect("prediction");
        let outside = predictor
            .evaluate(scheduled_now(), &[outbound(scheduled_now())], None)
            .expect("prediction");

        let upstream_score = |prediction: &BridgePrediction| {
            prediction
                .contributions
                .iter()
                .find(|item| item.kind == EvidenceKind::Outbound)
                .expect("outbound contribution")
                .applied_score
        };
        assert!((upstream_score(&inside) - upstream_score(&outside)).abs() < 0.001);
    }

    #[test]
    fn a_booked_tug_transit_lifts_the_blackout() {
        let now = blackout_now();
        let predictor = BridgePredictor::default();
        let transit = |exempt: bool| {
            evidence(
                "transit",
                "bbpilots.bridge.brickell",
                now,
                BridgeObservation::ScheduledTransit {
                    vessel: "PEPIN EXPRESS".into(),
                    exempt,
                    eta: Some(EtaRangeMinutes::new(0, 20)),
                },
            )
        };
        let exempt = predictor
            .evaluate(now, &[transit(true)], None)
            .expect("prediction");
        let ordinary = predictor
            .evaluate(now, &[transit(false)], None)
            .expect("prediction");

        let schedule_label = |prediction: &BridgePrediction| {
            prediction
                .contributions
                .iter()
                .find(|item| item.kind == EvidenceKind::Schedule)
                .expect("schedule contribution")
                .label
                .clone()
        };
        assert!(
            schedule_label(&exempt).contains("exempt"),
            "got {:?}",
            schedule_label(&exempt)
        );
        assert!(
            !schedule_label(&ordinary).contains("exempt"),
            "an unassisted movement must not inherit the exemption: {:?}",
            schedule_label(&ordinary)
        );
        assert!(exempt.confidence.basis_points > ordinary.confidence.basis_points);
    }

    #[test]
    fn an_imminent_slot_raises_the_schedule_contribution() {
        // Refused traffic queues and leaves together on the hour or half-hour,
        // so the minutes before a slot are the likeliest time for an opening.
        let predictor = BridgePredictor::default();
        let near = millis("2026-08-14T19:52:00Z"); // 15:52 EDT, 8 min to 16:00.
        let far = millis("2026-08-14T19:35:00Z"); // 15:35 EDT, 25 min to 16:00.
        let score = |at: TimestampMillis| {
            predictor
                .evaluate(at, &[], None)
                .expect("prediction")
                .contributions
                .iter()
                .find(|item| item.kind == EvidenceKind::Schedule)
                .expect("schedule contribution")
                .applied_score
        };
        assert!(
            score(near) > score(far),
            "{} should beat {}",
            score(near),
            score(far)
        );
    }

    #[test]
    fn an_ordinary_arrival_waits_for_the_next_legal_slot() {
        // 18:22 EDT on a weekday is inside the hour/half-hour period. An
        // arrival window of 10 to 21 minutes lands at 18:32 to 18:43, which has
        // already missed 18:30, so an ordinary vessel opens the bridge at 19:00.
        // Reporting T-10 promises a time the bridge cannot legally open.
        let now = millis("2026-08-14T22:22:00Z");
        let prediction = BridgePredictor::default()
            .evaluate(
                now,
                &[evidence(
                    "outbound",
                    "fl511.bridge.brickell",
                    now,
                    BridgeObservation::OutboundProgress {
                        bridge: "NW 5 ST".into(),
                        stage: OutboundProgressStage::High,
                        eta: Some(EtaRangeMinutes::new(10, 21)),
                    },
                )],
                None,
            )
            .expect("prediction");
        let eta = prediction.eta.expect("an eta");
        assert_eq!(eta.earliest, 38, "18:22 to 19:00 is 38 minutes");
        assert_eq!(eta.latest, 38);
    }

    #[test]
    fn an_exempt_transit_keeps_its_own_arrival_window() {
        // A tug with a tow opens the bridge when it arrives; that is the whole
        // point of the exemption, so its window must not be pushed to a slot.
        let now = millis("2026-08-14T22:22:00Z");
        let prediction = BridgePredictor::default()
            .evaluate(
                now,
                &[evidence(
                    "transit",
                    "bbpilots.bridge.brickell",
                    now,
                    BridgeObservation::ScheduledTransit {
                        vessel: "PEPIN EXPRESS".into(),
                        exempt: true,
                        eta: Some(EtaRangeMinutes::new(10, 21)),
                    },
                )],
                None,
            )
            .expect("prediction");
        let eta = prediction.eta.expect("an eta");
        assert_eq!((eta.earliest, eta.latest), (10, 21));
    }

    #[test]
    fn an_on_signal_period_imposes_no_wait() {
        // Outside the restricted hours the bridge opens on signal, so the
        // arrival window is the answer.
        let now = millis("2026-08-15T14:00:00Z"); // Saturday, on signal.
        let prediction = BridgePredictor::default()
            .evaluate(
                now,
                &[evidence(
                    "outbound",
                    "fl511.bridge.brickell",
                    now,
                    BridgeObservation::OutboundProgress {
                        bridge: "SW 2 Ave".into(),
                        stage: OutboundProgressStage::VeryHigh,
                        eta: Some(EtaRangeMinutes::new(4, 9)),
                    },
                )],
                None,
            )
            .expect("prediction");
        let eta = prediction.eta.expect("an eta");
        assert_eq!((eta.earliest, eta.latest), (4, 9));
    }
}
